#!/bin/bash
# © Copyright IBM Corporation 2015.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

shut_down()
{
  echo "----------------------------------------"
  echo "The container is shutting down..."
  echo "----------------------------------------"

  # NODE_NAME=${NODENAME-IIBV10NODE}
  echo "----------------------------------------"
  echo "Stopping node $NODE_NAME..."
  mqsistop $NODE_NAME

  /usr/local/bin/iib-agent4docker.sh stop
  exit 0
}

/usr/local/bin/iib_manage.sh&

if [ "$LICENSE" = "accept" ]; then
  echo "----------------------------------------"
  echo "Starting Monitoring Agent for IIB..."
  echo "----------------------------------------"
  /usr/local/bin/iib-agent4docker.sh start

  trap shut_down SIGTERM SIGINT
  echo "----------------------------------------"
fi


#wait $!
while true; do : sleep 1; done
echo "Stopped gracefully....."
